version: '3.3'

services:
    web:
        image: php:8.2-apache
        restart: always
        volumes:
            # Your copy of Break the Bank needs to in the /var/www/html folder
            # of your local machine.
            - /var/www/html:/var/www/html
            #- /var/www/html/config/apache2:/etc/apache2
            - /var/www/html/config/php:/usr/local/etc/php
        ports:
            - 80:80
        container_name: www
        
    db:
        image: mariadb:10.11.11-jammy
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: hackme
        ports:
            - 3306:3306
        container_name: db